default_priority: 50
retry_limit: 2
poll_interval_ms: 1000

paths:
  jobs_processing: "jobs/processing"
  jobs_finished: "jobs/finished"
  database: "database/comfyui_agent.db"

comfyui:
  api_base_url: "http://127.0.0.1:8000"  # ComfyUI API endpoint
  timeout_seconds: 30000  # Maximum time to wait for job completion
