# ComfyUI Workflow Definitions
# Each workflow maps to a pre-saved ComfyUI template

T2I_flux1_krea:
  template_path: "workflows/T2I_flux1_krea.json"
  required_inputs: ["prompt", "seed"]
  description: "Flux1 Krea text-to-image generation"

wf_realistic_portrait:
  template_path: "workflows/wf_realistic_portrait.json"
  required_inputs: ["prompt", "seed", "steps"]
  description: "Generates realistic portrait images"

wf_anime_style:
  template_path: "workflows/wf_anime_style.json"
  required_inputs: ["prompt", "seed", "steps", "style_strength"]
  description: "Generates anime-style artwork"

wf_t2v_cinematic:
  template_path: "workflows/wf_t2v_cinematic.json"
  required_inputs: ["prompt", "seed", "duration", "fps"]
  description: "Text to video with cinematic quality"

wf_t2v_animation:
  template_path: "workflows/wf_t2v_animation.json"
  required_inputs: ["prompt", "seed", "frames"]
  description: "Text to animated video"

wf_tts_natural:
  template_path: "workflows/wf_tts_natural.json"
  required_inputs: ["text", "voice_model", "speed"]
  description: "Natural text-to-speech generation"

wf_tts_character:
  template_path: "workflows/wf_tts_character.json"
  required_inputs: ["text", "character_voice", "emotion"]
  description: "Character voice synthesis"

wf_music_ambient:
  template_path: "workflows/wf_music_ambient.json"
  required_inputs: ["prompt", "duration", "bpm"]
  description: "Ambient music generation"

wf_music_cinematic:
  template_path: "workflows/wf_music_cinematic.json"
  required_inputs: ["prompt", "duration", "intensity"]
  description: "Cinematic soundtrack generation"

wf_3d_object:
  template_path: "workflows/wf_3d_object.json"
  required_inputs: ["prompt", "resolution", "format"]
  description: "3D object generation from text"

wf_3d_scene:
  template_path: "workflows/wf_3d_scene.json"
  required_inputs: ["prompt", "complexity", "lighting"]
  description: "Complete 3D scene generation"

ace-step-v1-t2a_lora:
  template_path: "workflows/ace-step-v1-t2a_lora.json"
  required_inputs: ["text"]
  description: "ACE Step v1 Text-to-Audio with LoRA"